---
- name: Configure app proxy settings
  become: yes 
  
  hosts: app 

  tasks: 
  - name:  Remove default config file
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent
    
  - name: Write settings to file
    blockinfile:
      path: /etc/nginx/conf.d/proxy_config_all.conf
      create: yes
      mode: "u=rw,g=r,o=r"      
      block: |     
      
            upstream app {
              server 192.168.73.15:8080;
            }

            server {

                listen 80;
                server_name app;

                location / {

                  proxy_pass              http://192.168.73.15:8080;
                  proxy_set_header        Host $host;
                  proxy_set_header        X-Real-IP $remote_addr;
                  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header        X-Forwarded-Proto $scheme;
              }
            }

  - name: Restart NGinx service
    service:
      name: nginx
      state: restarted