---
- name: Configure Jenkins Job
  hosts: localhost
  become: yes

  tasks:
  
  - name: Check jenkins service
    service:
      name: jenkins
        state: started

  - name: Create jenkins credentials
    shell: /vagrant/jenkins_creds.sh
    become_user: root
    
  - name: Create jenkins job
    shell: /vagrant/create_jenkins_job.sh